#ifndef ESOLDER_CONSTANTS_H_
#define ESOLDER_CONSTANTS_H_


#define ESOLDER_TEMP_SET_MAX        500
#define ESOLDER_TEMP_SET_MIN        50
#define ESOLDER_TEMP_SET_DEFAULT    250
#define ESOLDER_TEMP_SET_STEP       5
#define ESOLDER_TEMP_SET_BIGSTEP    10

#define ESOLDER_FLOW_SET_MAX        100
#define ESOLDER_FLOW_SET_MIN        0
#define ESOLDER_FLOW_SET_DEFAULT    70
#define ESOLDER_FLOW_SET_STEP       5
#define ESOLDER_FLOW_SET_BIGSTEP    10


#endif // !ESOLDER_CONSTANTS_H_
