#include "stm32f4xx.h"
#include "GPIO.h"

void MCU_init(void){
    RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIOARST;
    RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIOBRST;
    RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIOCRST;
    RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIODRST;
    RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIOERST;
    RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIOFRST;

    RCC->AHB1RSTR &= ~RCC_AHB1RSTR_GPIOARST;
    RCC->AHB1RSTR &= ~RCC_AHB1RSTR_GPIOBRST;
    RCC->AHB1RSTR &= ~RCC_AHB1RSTR_GPIOCRST;
    RCC->AHB1RSTR &= ~RCC_AHB1RSTR_GPIODRST;
    RCC->AHB1RSTR &= ~RCC_AHB1RSTR_GPIOERST;
    RCC->AHB1RSTR &= ~RCC_AHB1RSTR_GPIOFRST;

    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOBEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOFEN;
    
    RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
    RCC->APB1ENR |= RCC_APB1ENR_SPI3EN;
    
    RCC->AHB1ENR |= RCC_AHB1ENR_DMA2EN;
    
    RCC->APB2ENR |= RCC_APB2ENR_TIM8EN;
}